name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Check if PR is ready for auto-merge
      id: check-pr
      run: |
        # Only auto-merge patch and minor version updates
        if [[ "${{ github.event.pull_request.title }}" =~ ^Bump.*from.*to.* ]]; then
          # Extract version numbers from PR title
          title="${{ github.event.pull_request.title }}"
          
          # Check if it's a patch or minor update (not major)
          if [[ $title =~ ([0-9]+)\.([0-9]+)\.([0-9]+).*to.*([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            old_major=${BASH_REMATCH[1]}
            new_major=${BASH_REMATCH[4]}
            
            if [[ $old_major == $new_major ]]; then
              echo "safe-update=true" >> $GITHUB_OUTPUT
            else
              echo "safe-update=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "safe-update=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "safe-update=false" >> $GITHUB_OUTPUT
        fi

    - name: Wait for CI checks
      if: steps.check-pr.outputs.safe-update == 'true'
      uses: fountainhead/action-wait-for-check@v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: 'All Checks Passed'
        ref: ${{ github.event.pull_request.head.sha }}
        timeoutSeconds: 1200

    - name: Auto-merge Dependabot PR
      if: steps.check-pr.outputs.safe-update == 'true'
      run: |
        gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment on major version updates
      if: steps.check-pr.outputs.safe-update == 'false'
      run: |
        gh pr comment "${{ github.event.pull_request.html_url }}" --body "⚠️ This appears to be a major version update. Please review manually before merging."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}